services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: migration-link-exchange-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  api:
    image: ghcr.io/ministryofjustice/migration-link-exchange-api:${APP_VERSION:-latest}
    build:
      context: ../
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http:/api:8080/health/ping"]
      interval: 5s
      retries: 100
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DB_ENDPOINT: postgres:5432
      DB_NAME: migration-link-exchange-db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
