generic-service:
  nameOverride: migration-link-exchange-api
  productId: "UNASSIGNED" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/migration-link-exchange-api
    tag: app_version # override at deployment time
    port: 8080

  serviceAccountName: "migration-link-exchange-sa"

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: migration-link-exchange-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    S3_REGION: "eu-west-2"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    migration-link-exchange-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

    rds-postgresql-instance-output:
      DB_ENDPOINT: rds_instance_endpoint
      DB_NAME: database_name
      DB_USERNAME: database_username
      DB_PASSWORD: database_password

    migration-link-exchange-api:
      APP_MIGRATION_CSV_URL: migration_csv_url

    s3-bucket-output:
      S3_BUCKET: bucket_name

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: migration-link-exchange-api
