---
# Per environment values which override defaults in migration-link-exchange-api/values.yaml

generic-service:
  # Temporarily set replica count to 1, during data migration phase.
  # replicaCount: 1

  ingress:
    enabled: false

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: PROD_ALERTS_SEVERITY_LABEL
